modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
authors="ustc-zzzz"
version="${file.jarVersion}"
modId="atlantis_mod"
displayName="Atlantis Mod"
description="Atlantis Mod"

[[dependencies.fluidbypassrenderdemo]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.fluidbypassrenderdemo]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
